area52/Models/Db.cs
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using Dapper;
using MySql.Data.MySqlClient;

namespace area52.Models
{
    public static class Db
    {
        private static string ConnectionString =>
            ConfigurationManager.ConnectionStrings["Area52"].ConnectionString;

        private static IDbConnection Open()
        {
            var conn = new MySqlConnection(ConnectionString);
            conn.Open();
            return conn;
        }

        public static IEnumerable<T> Query<T>(string sql, object param = null)
        {
            using (var conn = Open())
            {
                return conn.Query<T>(sql, param);
            }
        }

        public static int Execute(string sql, object param = null)
        {
            using (var conn = Open())
            {
                return conn.Execute(sql, param);
            }
        }
    }
}

area52/Models/ReservationModel.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using Dapper;
using MySql.Data.MySqlClient;

namespace area52.Models
{
    public class ReservationModel
    {
        private static string ConnectionString =>
            ConfigurationManager.ConnectionStrings["Area52"].ConnectionString;
        
        // Properties for form input
        public int Reservering_ID { get; set; }
        public int GastID { get; set; }
        public int Aantal_Personen { get; set; }
        public DateTime Reserveringsdatum { get; set; }
        public decimal Totaal_Bedrag { get; set; }
        public string Opmerkingen { get; set; }

        // Get all reservations
        public static IEnumerable<ReservationModel> GetReservations()
        {
            using (var connection = new MySqlConnection(ConnectionString))
            {
                connection.Open();
                return connection.Query<ReservationModel>(@"
                    SELECT  R.Reservering_ID
                            ,R.GastID
                            ,R.Aantal_Personen
                            ,R.Reserveringsdatum
                            ,R.Totaal_Bedrag
                            ,R.Opmerkingen
                    FROM Reservering R
                    ORDER BY R.Reservering_ID DESC
                    LIMIT 10;"
                );
            }
        }

        // Create new reservation from form data
        public static int CreateReservation(int aantalpersonen, DateTime reserveringsdatum, string opmerkingen)
        {
            // Transform form data to variables
            int aantal = aantalpersonen;
            DateTime datum = reserveringsdatum;
            string opmerking = opmerkingen ?? string.Empty;
            decimal totaalBedrag = aantal * 20; 
            int gastID = 1;

            using (var connection = new MySqlConnection(ConnectionString))
            {
                connection.Open();
                
                var result = connection.Execute(@"
                    INSERT INTO Reservering (GastID, Aantal_Personen, Reserveringsdatum, Totaal_Bedrag, Opmerkingen)
                    VALUES (@GastID, @AantalPersonen, @ReserveringsDatum, @TotaalBedrag, @Opmerkingen);
                    SELECT LAST_INSERT_ID();",
                    new
                    {
                        GastID = gastID
                        ,AantalPersonen = aantal
                        ,ReserveringsDatum = datum
                        ,TotaalBedrag = totaalBedrag
                        ,Opmerkingen = opmerking
                    }
                );

                return result;
            }
        }
        
        public static ReservationModel FillForm(int id)
        {
            using (var connection = new MySqlConnection(ConnectionString))
            {
                connection.Open();

                return connection.QuerySingleOrDefault<ReservationModel>(@"
            SELECT  R.Reservering_ID,
                    R.GastID,
                    R.Aantal_Personen,
                    R.Reserveringsdatum,
                    R.Totaal_Bedrag,
                    R.Opmerkingen
            FROM Reservering R
            WHERE R.Reservering_ID = @Id
            LIMIT 1;",
                    new
                    {
                        Id = id
                    }
                );
            }
        }
    }
}

area52/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace area52.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
    }
}

area52/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using area52.Models;

namespace area52.Controllers
{
    public class ReservationController : Controller
    {

        public ActionResult Index()
        {
            var reservations = ReservationModel.GetReservations();
            return View(reservations);
        }

        public ActionResult Form(int? id)
        {
            ReservationModel model = new ReservationModel();
            if (id.HasValue)
            {
                var reservation = model.FillForm(id.Value);

                return View(reservation);
            }
            
            
            return View();
        }

        [HttpPost]
        public ActionResult Create(int aantal_personen, DateTime reserveringsdatum, string opmerkingen)
        {
            try
            {
                
                if (aantal_personen <= 0)
                    return RedirectToAction("Form", new { status = "zeromembercount" });

                if (reserveringsdatum < DateTime.Today)
                    return RedirectToAction("Form", new { status = "reservationinpast" });

                // Roep model aan om reservering aan te maken
                int reserveringID = ReservationModel.CreateReservation(aantal_personen, reserveringsdatum, opmerkingen);


                return RedirectToAction("Index", new { status = "succes" });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Form", new { status = $"Error: {ex.Message}" });
            }
        }
    }
}

area52/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

area52/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    My Company Address
</address>

area52/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p>
        <a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a>
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p>
            <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p>
            <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p>
            <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a>
        </p>
    </div>
</div>

area52/Views/Reservation/Form.cshtml
@{
    ViewBag.Title = "Reservering";
    
}

@model area52.Models.ReservationModel

<div class="container">
    <h2>Nieuwe Reservering</h2>
    
    <form method="post" action="/Reservation/Create">
        <div class="form-group">
            <label for="aantal_personen">Aantal Personen:</label>
            <input type="number" id="aantal_personen" name="aantal_personen" 
                   min="1" required class="form-control" />
        </div>

        <div class="form-group">
            <label for="reserveringsdatum">Reserveringsdatum:</label>
            <input type="date" id="reserveringsdatum" name="reserveringsdatum" 
                   required class="form-control" />
        </div>
        
        <div class="form-group">
            
            <label for="referencetype">Reseverings soort</label>
            <select id="referencetype" name="referencetype" required class="form-control">
                <option value="">-- Selecteer een waarde --</option>
                <option value="table">Restaurant</option>
                <option value="activity">Activiteit</option>
                <option value="housing">Huis</option>
            </select>
            
        </div>

        <div class="form-group">
            <label for="opmerkingen">Opmerkingen:</label>
            <textarea id="opmerkingen" name="opmerkingen" rows="5" 
                      class="form-control" placeholder="Voer hier uw opmerkingen in"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Reservering Plaatsen</button>
    </form>
</div>

area52/Views/Reservation/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    var status = Request.QueryString["status"];
}
@model IEnumerable<area52.Models.ReservationModel>

<h1>Reseveringen</h1>

@if (!string.IsNullOrEmpty(status))
{
    switch (status)
    {
        case "zeromembercount":
            <div class="alert alert-warning">
                Er zijn te weinig deelnemers geselecteerd.
            </div>
            break;
        case "reservationinpast":
            <div class="alert alert-warning">
                Reservering is opgeslagen.
            </div>
            break;

        case "success":
            <div class="alert alert-success">
                Reservering is opgeslagen.
            </div>
            break;

        default:
            break; // of laat default weg als je niks wil tonen
    }

}

<a href="@Url.Action("Form", "Reservation")" class="btn btn-lg btn-primary">
    <i class="fa fa-plus"></i> Reservering
</a>

<hr/>

<table class="table">
    <thead>
    <tr class="row">
        <th class="col-1">Gast id</th>
        <th class="col-2">Totaal bedrag</th>
        <th class="col-1">Aantal personen</th>
        <th class="col-3">Datum</th>
        <th class="col-3">Opmerking</th>
        <th class="col-1">update</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var Reservering in Model)
    {
        <tr class="row">
            <td class="col-1">@Reservering.GastID</td>
            <td class="col-2">@Reservering.Totaal_Bedrag</td>
            <td class="col-1">@Reservering.Aantal_Personen</td>
            <td class="col-3">@Reservering.Reserveringsdatum</td>
            <td class="col-3 text-nowrap">@Reservering.Opmerkingen</td>
            <td class="col-1 text-nowrap">
                <a href="@Url.Action("Form", "Reservation", new { id = @Reservering.Reservering_ID })" class="btn btn-lg btn-primary">
                    <i class="fa fa-pencil"></i>
                </a>
                
            </td>
        </tr>
    }
    </tbody>
</table>

area52/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
<div class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Area 52", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <!-- HOME dropdown -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Home <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </li>

                <!-- RESERVATION dropdown -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Reservation <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("All reservations", "Index", "Reservation")</li>
                        <li>@Html.ActionLink("Create reservation", "Form", "Reservation")</li>
                        @* add more as needed *@
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</div>
<div class="container body-content mt-5">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.2026 - Timo Bergthaler</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>